
CREATE DATABASE LIBRARY; 
USE LIBRARY;

CREATE TABLE Customers(
customer_id INT PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(50),
email VARCHAR(100),
city VARCHAR(50)
);

CREATE TABLE Books(
book_id INT PRIMARY KEY AUTO_INCREMENT,
title VARCHAR(100),
author VARCHAR(50),
price INT
);

CREATE TABLE Orders(
order_id INT PRIMARY KEY AUTO_INCREMENT,
customer_id INT,
book_id INT,
quantity INT,
order_date DATE,

FOREIGN KEY (customer_id) REFERENCES Customers(customer_id),
FOREIGN KEY (book_id) REFERENCES Books(book_id)
);

INSERT INTO Customers (name,email,city) VALUES
('Ali Khan','ali@gmail.com','Karachi'),
('Sara Ahmed','sara@gmail.com','Lahore'),
('Ahmed Raza','ahmed@gmail.com','Islamabad'),
('Fatima Noor','fatima@gmail.com','Karachi'),
('Bilal Hussain','bilal@gmail.com','Multan'),
('Ayesha Malik','ayesha@gmail.com','Lahore'),
('Usman Tariq','usman@gmail.com','Faisalabad'),
('Hassan Ali','hassan@gmail.com','Karachi');

INSERT INTO Books (title,author,price) VALUES
('Python for Beginners','John Smith',3000),
('SQL Mastery','David Miller',3500),
('Data Science Guide','Sarah Lee',5000),
('Machine Learning Basics','Andrew Clark',4500),
('Deep Learning Explained','Michael Brown',5500),
('Web Development Bootcamp','Chris Evans',2800),
('Cyber Security Handbook','Robert King',4000),
('AI Fundamentals','Lisa Ray',5200);

INSERT INTO Orders (customer_id,book_id,quantity,order_date) VALUES
(1,1,2,'2025-01-10'),
(1,3,1,'2025-01-15'),
(2,2,1,'2025-01-18'),
(2,4,2,'2025-01-22'),
(3,5,1,'2025-02-01'),
(3,1,1,'2025-02-03'),
(4,3,2,'2025-02-10'),
(5,6,1,'2025-02-12'),
(6,7,2,'2025-02-15'),
(7,8,1,'2025-02-18'),
(8,2,3,'2025-02-20'),
(8,5,1,'2025-02-22');

-- 1️⃣ Show Customer Name and Book Title

SELECT C.name, B.title
FROM Orders O
JOIN Customers C
ON O.customer_id = C.customer_id
JOIN Books B
ON O.book_id = B.book_id;

-- 2️⃣ Total Books Ordered by Each Customer

SELECT C.name, SUM(O.quantity) AS total_books
FROM Customers C
JOIN Orders O
ON C.customer_id = O.customer_id
GROUP BY C.name;

-- 3️⃣ Find the Most Expensive Book

SELECT title, price
FROM Books
WHERE price = (
SELECT MAX(price)
FROM Books
);

-- 4️⃣ Customer Who Ordered the Most Books

SELECT C.name, SUM(O.quantity) AS total_books
FROM Customers C
JOIN Orders O
ON C.customer_id = O.customer_id
GROUP BY C.name
ORDER BY total_books DESC
LIMIT 1;

-- 5️⃣ Books That Were Never Ordered

SELECT B.title
FROM Books B
LEFT JOIN Orders O
ON B.book_id = O.book_id
WHERE O.order_id IS NULL;

-- 6️⃣ Total Revenue Generated by Each Book

SELECT B.title,
SUM(B.price * O.quantity) AS total_revenue
FROM Books B
JOIN Orders O
ON B.book_id = O.book_id
GROUP BY B.title
ORDER BY total_revenue DESC;

-- ️⃣ Customers Who Ordered Books More Expensive Than Average

SELECT DISTINCT C.name
FROM Customers C
JOIN Orders O
ON C.customer_id = O.customer_id
JOIN Books B
ON O.book_id = B.book_id
WHERE B.price > (
SELECT AVG(price)
FROM Books
);

-- 8️⃣ Book That Generated the Highest Revenue

SELECT B.title,
SUM(B.price * O.quantity) AS highest_revenue
FROM Books B
JOIN Orders O
ON B.book_id = O.book_id
GROUP BY B.title
ORDER BY highest_revenue DESC
LIMIT 1;

-- 9️⃣ Total Orders From Each City

SELECT C.city,
COUNT(O.order_id) AS total_orders
FROM Customers C
JOIN Orders O
ON C.customer_id = O.customer_id
GROUP BY C.city;

-- 🔟 Top 3 Customers Who Spent the Most Money

SELECT C.name,
SUM(B.price * O.quantity) AS total_spent
FROM Customers C
JOIN Orders O
ON C.customer_id = O.customer_id
JOIN Books B
ON O.book_id = B.book_id
GROUP BY C.name
ORDER BY total_spent DESC
LIMIT 3;

-- ⭐ Bonus: Create a View

CREATE VIEW Order_Details AS
SELECT
C.name,
B.title,
O.quantity,
B.price,
(B.price * O.quantity) AS total_cost
FROM Orders O
JOIN Customers C
ON O.customer_id = C.customer_id
JOIN Books B
ON O.book_id = B.book_id;

-- To use the view:

SELECT * FROM Order_Details;